/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import static org.junit.jupiter.api.Assertions.assertEquals;

import org.easymock.EasyMock;
import org.easymock.internal.MocksControl.MockType;
import org.junit.jupiter.api.Test;

public class MockoTest {
    
    @Test
	public void exampleOneNice() {
		Mocko obj = EasyMock.createNiceMock(Mocko.class);
        EasyMock.expect(obj.getSquare()).andReturn(15);
        EasyMock.expect(obj.getCube()).andReturn(20);
        //EasyMock.expect(obj.third()).andReturn(7);
        EasyMock.replay(obj);
        
        //Ominiecie metody daje AssertionError
        
        //Odwracamy kolejnosc
        assertEquals(20, obj.getCube());
        assertEquals(15, obj.getSquare());
        //Unexpected call
        assertEquals(0, obj.getSquare());
        assertEquals(0, obj.getCube());
        
        //Wszystko dziala
        
        EasyMock.verify(obj);
	}
    
    @Test
	public void exampleOneStrict() {
		Mocko obj = EasyMock.createStrictMock(Mocko.class);
        EasyMock.expect(obj.getSquare()).andReturn(15);
        EasyMock.expect(obj.getCube()).andReturn(17);
        EasyMock.replay(obj);
        
        //W przypadku braku wywolania metody - Assertion Error

      
        //W przypadku zmiany kolejnosci dostajemy AssertionError
        	//assertEquals(17,obj.getCube());
        assertEquals(15, obj.getSquare());
        
        //W przypadku kolejnego asserta z obj.getSquare dostajemy AssertionError
        	//assertEquals(15, obj.getSquare());
        assertEquals(17,obj.getCube());
        
        EasyMock.verify(obj);
	}
    
    @Test
	public void exampleOneDefault() {
		Mocko obj = EasyMock.createMock(Mocko.class);
        EasyMock.expect(obj.getSquare()).andReturn(15);
        EasyMock.expect(obj.getCube()).andReturn(10);
        EasyMock.replay(obj);
        
        //W przypadku braku wywolania metody - Assertion Error
        
        //Zmieniona kolejnosc : wszystko dziala
        assertEquals(10, obj.getCube());
        assertEquals(15, obj.getSquare());
        //Unexpected call  - Assertion Error
        	//assertEquals(10, obj.getCube());
        
        EasyMock.verify(obj);
       	}
}
